fix: missing `onSave` prop for MediaSettingsModal in Images layout (#181)
* fix: missing `onSave` prop for MediaSettingsModal in Images layout

This commit adds the `onSave` prop for the two uses of MediaSettingsModal
in the Images layout. Previously, we got the following error message:

Unhandled Rejection (TypeError): onSave is not a function

because the prop was not defined.

This commit also sets the `onSave` as a required prop type.

* fix: missing `onSave` prop for MediaSettingsModal in Files layout

Refer to previous commit message.

Co-authored-by: Jie Hao Kwa <jiehaokwa@Jies-MacBook-Pro.local>